gui-rows: 6
gui-title: "&#FF5733&lBalance Leaderboard"
gui-contents:
  filler:
    slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 17
      - 18
      - 26
      - 27
      - 35
      - 36
      - 44
      - 45
      - 46
      - 47
      - 48
      - 49
      - 50
      - 51
      - 52
      - 53
    material: BLACK_STAINED_GLASS_PANE
    name: " "
    lore: []
  test:
    slots: 49
    material: RED_STAINED_GLASS_PANE
    name: " "
    lore: []
top-tracker-amount: 10
top-tracker-slots:
  - 11
  - 12
  - 13
  - 14
  - 15
  - 20
  - 21
  - 22
  - 23
  - 24
self-ranking: true
self-slot: 40
# PLACEHOLDERS
# %player-name% - displays player's name
# %player-bal% - displays player's balance
# %ranking% - displays player's ranking
head-name: "&e%player-name% &8(&7%ranking%&8)"
head-lore:
  - "&7Balance&8: &a%player-bal%"
  - "&7Placement&8: &e%ranking%"
head-name-empty: "&7None"
head-lore-empty:
  - "&7You can fill this spot!"
head-texture-empty: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkYzA0OGE3Y2U3OGY3ZGFkNzJhMDdkYTI3ZDg1YzA5MTY4ODFlNTUyMmVlZWQxZTNkYWYyMTdhMzhjMWEifX19"
